### ISSUE TITLE
Cannot open files of type ""

### ISSUE THREAD

**Issue by VioletGiraffe** [rochus-keller/LeanCreator#2]
I'm very excited about the LeanQt project, I think it's very cool. But for every single of my projects, I get this error when trying to open the .pro file: 

![image](https://user-images.githubusercontent.com/1175926/221372650-94d98178-9693-4aa1-9211-d34bc129377c.png)

Something wrong with MIME type detection, perhaps?.. This is running the pre-built Win x64 version I downloaded via the link in the README.

**Comment by VioletGiraffe** [comment]
Sorry, just realized, I didn't notice this part: "No support planned for qmake". That's a pity, to put it mildly. Would it be difficult to add qmake support?

**Comment by rochus-keller** [comment]
LeanCreator doesn't support qmake, as noted in the readme (see https://github.com/rochus-keller/LeanCreator#no-support-planned). If you need qmake support, you can e.g. translate the BUSY specifications to qmake .pro files using the command line `lua build.lua <yourproject> -G qmake` and use LeanQt with Qt Creator, or just compile LeanQt with BUSY and use the static or dynamic LeanQt library.

**Comment by rochus-keller** [comment]
> Would it be difficult to add qmake support?

Well, it would be feasible, but by the end of the day I would just replicate Qt Creator, which doesn't make much sense.

**Comment by VioletGiraffe** [comment]
You could say the same about LeanQt - "it just replicates Qt". But there is a value in being lightweight and maintainable, I think we both appreciate that.
Is  LeanCreator even supposed to work with other projects than LeanQt itself? Does it support the MSVC toolchain?

**Comment by rochus-keller** [comment]
> You could say the same about LeanQt - "it just replicates Qt"

LeanQt is not just a subset of Qt, but it was refactored and redesigned to meet my goals; a lot of changes would not have been feasible in Qt because of binary compatibility requirements; I still maintain API compatibility, but on compiler, not on binary level.

> Does it support the MSVC toolchain? 

Sure. You can e.g. download the Windows x86 or x86_64 precompiled binary (or build it yourself) and it will find the MSVC toolchain on the Windows machine and use it. Also the debugger fully works.

> Can I use it for developing my own projects if I use your BUSY build system?

Sure, that's the idea. See https://github.com/rochus-keller/BUSY#readme for more information.
